sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky-take-out
    username: root
    password: "187367"

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
